/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Type of data being requested
 */
export type Schema = string;
/**
 * Should the user select the data to be returned?
 */
export type UserSelectsTheData = boolean;
/**
 * Limit the number of data records the user can return. Limit is optional.
 */
export type UserSelectLimit = number;
/**
 * Label of the action
 */
export type Label = string;
/**
 * The user will be redirected to this URL if they decide to use this suggested fallback action
 */
export type URL = string;
export type Status = "accept" | "reject";

/**
 * An inbox message requesting specific data from a user
 */
export interface DataRequest {
  requestSchema: Schema;
  filter?: Filter;
  userSelect?: UserSelectsTheData;
  userSelectLimit?: UserSelectLimit;
  fallbackAction?: FallbackAction;
  status?: Status;
  [k: string]: unknown;
}
/**
 * Database filter the data must match
 */
export interface Filter {
  [k: string]: unknown;
}
/**
 * An action suggested to the user if they don't have the requested data
 */
export interface FallbackAction {
  label: Label;
  url: URL;
  [k: string]: unknown;
}
