/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id of the task allocated by the allocator node
 */
export type AppID = string;
/**
 * ID of http provider
 *
 * @minItems 1
 */
export type HttpProviderId = [string, ...string[]];
/**
 * Values of public fields defined in schema
 *
 * @minItems 1
 */
export type Proofs = [
  {
    identifier: Identifier;
    claimData: ClaimData;
    signature: Signature;
    witnesses?: Witnesses;
    [k: string]: unknown;
  },
  ...{
    identifier: Identifier;
    claimData: ClaimData;
    signature: Signature;
    witnesses?: Witnesses;
    [k: string]: unknown;
  }[]
];
/**
 * Identifier of provider
 */
export type Identifier = string;
/**
 * Protocol of request
 */
export type Protocol = string;
/**
 * Stringfied JSON object of parameters and API reqeusts
 */
export type ParametersOfRequest = string;
/**
 * Identifier of request
 */
export type IdentifierOfRequest = string;
/**
 * Epoch of request
 */
export type EpochOfRequest = string;
/**
 * The signature of verification credential
 *
 * @minItems 1
 */
export type Signature = [string, ...string[]];
/**
 * Witness
 *
 * @minItems 1
 */
export type Witnesses = [
  {
    id: ID;
    url: URL;
    [k: string]: unknown;
  },
  ...{
    id: ID;
    url: URL;
    [k: string]: unknown;
  }[]
];
/**
 * ID
 */
export type ID = string;
/**
 * URL
 */
export type URL = string;
/**
 * Session Id of process
 */
export type SessionId = string;
/**
 * The ID of reclaim provider
 */
export type ReclaimProviderID = string;
/**
 * The label of reclaim provider
 */
export type ReclaimProviderLabel = string;
/**
 * DID of the subject
 */
export type Did = string;

/**
 * A schema for reclaim protocol credential
 */
export interface SchemaForReclaimProtocol {
  appId: AppID;
  httpProviderId?: HttpProviderId;
  proofs: Proofs;
  sessionId: SessionId;
  reclaimProviderId: ReclaimProviderID;
  reclaimProviderLabel: ReclaimProviderLabel;
  id: Did;
  [k: string]: unknown;
}
/**
 * Verifiable credential data
 */
export interface ClaimData {
  provider: Protocol;
  parameters?: ParametersOfRequest;
  identifier: IdentifierOfRequest;
  epoch?: EpochOfRequest;
  [k: string]: unknown;
}
