/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A generic schema for playlists from platforms like Spotify, YouTube, etc.
 */
export type Playlist = BaseSchema & {
  type: Type;
  owner?: Person;
  tracks?: Tracks;
  [k: string]: unknown;
};
/**
 * Name of the item within card list and details
 */
export type Name = string;
/**
 * Brief summary of item
 */
export type Summary = string;
/**
 * Is this record archived?
 */
export type Archived = boolean;
/**
 * URI of the schema for this record
 */
export type Schema = string;
/**
 * Name of the application this data was sourced from
 */
export type SourceApplication = string;
/**
 * ID of the account from the original data source
 */
export type SourceAccountID = string;
/**
 * ID from the original data source
 */
export type SourceID = string;
/**
 * URL of an icon for this record. Must be square, prefer SVG, otherwise minimum 50p x 50p
 */
export type Icon = string;
/**
 * Additional text that should be indexed for search purposes
 */
export type IndexableText = string;
/**
 * Date/time this record was inserted
 */
export type Inserted = string;
/**
 * Date/time this record was modified
 */
export type Modified = string;
/**
 * Type of the playlist or track, either audio or video
 */
export type Type = "audio" | "video";
/**
 * Unique identifier for the track/video
 */
export type TrackID = string;
/**
 * Title of the track/video
 */
export type Title = string;
/**
 * Name of the artist or content creator
 */
export type ArtistCreator = string;
/**
 * Album name (if applicable, e.g., for Spotify)
 */
export type Album = string;
/**
 * URL of the thumbnail image
 */
export type Thumbnail = string;
/**
 * Duration of the track/video in milliseconds
 */
export type Duration = number;
/**
 * Direct URL to the track/video
 */
export type URL = string;
/**
 * Array of track or video items in the playlist
 */
export type Tracks = Track[];

/**
 * A base schema
 */
export interface BaseSchema {
  name?: Name;
  summary?: Summary;
  archived?: Archived;
  schema: Schema;
  signatures?: Signatures;
  sourceApplication?: SourceApplication;
  sourceAccountId?: SourceAccountID;
  sourceId?: SourceID;
  sourceData?: SourceData;
  icon?: Icon;
  indexableText?: IndexableText;
  insertedAt?: Inserted;
  modifiedAt?: Modified;
  [k: string]: unknown;
}
/**
 * Signatures verifying this data has been signed
 */
export interface Signatures {
  [k: string]: unknown;
}
/**
 * Raw data from the original source
 */
export interface SourceData {
  [k: string]: unknown;
}
/**
 * Schema representing a person
 */
export interface Person {
  /**
   * Email address of the person
   */
  email?: string;
  /**
   * Display name of the person
   */
  displayName: string;
  [k: string]: unknown;
}
/**
 * Schema representing a track or video in the playlist
 */
export interface Track {
  id: TrackID;
  title: Title;
  artist?: ArtistCreator;
  album?: Album;
  thumbnail?: Thumbnail;
  duration?: Duration;
  url?: URL;
  type?: Type;
  [k: string]: unknown;
}
