/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Symmetric encryption key as a hex string
 */
export type Key = string;
/**
 * Type of symmetric encryption key
 */
export type Type = string;

/**
 * A symmetric key
 */
export interface SymmetricKey {
  key: Key;
  type: Type;
  [k: string]: unknown;
}
