/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Name of this item
 */
export type Name = string;
/**
 * Is this record archived?
 */
export type Archived = boolean;
/**
 * Schema used for this record
 */
export type Schema = string;
/**
 * Name of the application this data was sourced from
 */
export type SourceApplication = string;
/**
 * Date/time this record was inserted
 */
export type Inserted = string;
/**
 * Date/time this record was modified
 */
export type Modified = string;

/**
 * A base schema
 */
export interface BaseSchema {
  displayName?: Name;
  archived?: Archived;
  schema?: Schema;
  signatures?: Signatures;
  sourceApplication?: SourceApplication;
  insertedAt?: Inserted;
  modifiedAt?: Modified;
  [k: string]: unknown;
}
/**
 * Signatures verifying this data has been signed
 */
export interface Signatures {
  [k: string]: unknown;
}
