/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Content = string;
export type PublicKey = string;

/**
 * An unprocessed, encrypted inbox item in a users public inbox
 */
export interface EncryptedInboxMessage {
  content: Content;
  key: PublicKey;
  [k: string]: unknown;
}
