/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * DID JWT representation of this credential
 */
export type DIDJWTVerifiableCredential = string;

export interface Credential {
  didJwtVc: DIDJWTVerifiableCredential;
  [k: string]: unknown;
}
