/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FinClusiveId = string;
export type FirstName = string;
export type LastName = string;
export type StreetAddress = string;
export type Suburb = string;
export type State = string;
export type PostCode = string;
/**
 * YYYY-MM-DD
 */
export type DateOfBirth = string;
export type ComplianceProfileLevel = string;
export type ComplianceStatus = string;
/**
 * YYYY-MM-DD
 */
export type CreationDate = string;
/**
 * YYYY-MM-DD
 */
export type ValidUntil = string;
export type FinClusiveComplianceApiUrl = string;

export interface FinClusiveBasicIndividualKYC {
  finClusiveId?: FinClusiveId;
  firstName: FirstName;
  lastName?: LastName;
  streetAddress1?: StreetAddress;
  suburb?: Suburb;
  state?: State;
  postcode?: PostCode;
  dateOfBirth?: DateOfBirth;
  complianceProfileLevel?: ComplianceProfileLevel;
  complianceStatus?: ComplianceStatus;
  creationDate?: CreationDate;
  validUntil?: ValidUntil;
  finClusiveComplianceApiUrl?: FinClusiveComplianceApiUrl;
  [k: string]: unknown;
}
