/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This example value set defines a set of codes that can be used to indicate the role of a Practitioner.
 */
export interface PractitionerRole {
  [k: string]: unknown;
}
